### ISSUE TITLE
赞！不过哥，我感觉每天一次的粒度是不是削微有点粗？

### ISSUE THREAD

**Issue by wangdahoo** [justjavac/weibo-trending-hot-search#1]
2小时一次，日榜再按各个分时中的每个item热度值来ranking一下是不是好一些？

**Comment by justjavac** [comment]
每小时抓取一次，根据 yyyy-mm-dd 归档

**Comment by justjavac** [comment]
https://github.com/justjavac/weibo-trending-hot-search/blob/master/.github/workflows/schedule.yml

```yml
on:
  schedule:
    - cron: "0 * * * *"
```

每小时一次
